// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iwjsnihjsmdddibudthf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3anNuaWhqc21kZGRpYnVkdGhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MzQ0MzAsImV4cCI6MjA2MDMxMDQzMH0.anOI-OrcNB-_OAPmUSmhZpuEwvQ76H25vzzB5rjWwu4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);